CREATE TABLE tb_lst_empresa (
    id_empresa    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cnpj          VARCHAR2(25),
    nome_fantasia VARCHAR2(100) NOT NULL,
    razao_social  VARCHAR2(100) NOT NULL,
    telefone      VARCHAR2(25),
    email         VARCHAR2(100) NOT NULL
);
