CREATE TABLE tb_lst_emprego (
    id_emprego            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_empresa            INTEGER NOT NULL,
    data_admissao         DATE NOT NULL,
    cargo                 VARCHAR2(100) NOT NULL,
    tipo_contrato         VARCHAR2(30) NOT NULL,
    carga_horaria_semanal INTEGER NOT NULL,
    modelo_trabalho       VARCHAR2(25) NOT NULL,
    satisfacao_trabalho   INTEGER NOT NULL
);

