CREATE TABLE tb_lst_perfil (
    id_perfil    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome_perfil   VARCHAR2(75) NOT NULL,
    desc_perfil   VARCHAR2(75) NOT NULL,
    CONSTRAINT tb_lst_perfil_pk PRIMARY KEY (id_perfil)
);