CREATE TABLE tb_lst_usuario (
    id_usuario      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_perfil       INTEGER NOT NULL,
    id_emprego      INTEGER NOT NULL,
    nome_usuario    VARCHAR2(50),
    sobrenome       VARCHAR2(50),
    data_nascimento DATE NOT NULL,
    cpf             VARCHAR2(25) NOT NULL,
    telefone        VARCHAR2(25) NULL,
    email_usuario   VARCHAR2(75) NOT NULL,
    senha           VARCHAR2(100) NOT NULL
);
