-- V_NUMERO_SEGUINTE__Create_Checkins_Table.sql

CREATE TABLE TB_LST_CHECKINS (
    id                       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id                  NUMBER(19) NOT NULL,
    checkin_text             CLOB NOT NULL,
    status                   VARCHAR2(10) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    sentiment_result         VARCHAR2(255),
    classification_score     FLOAT(126),
    created_at               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_checkins PRIMARY KEY (id)
);
CREATE INDEX idx_checkin_user_id ON TB_LST_CHECKINS (user_id);